[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antlr-rust = "=0.3.0-beta"
clap = { version = "4.0.17", features = ["derive"] }
comfy-table = "6.1.3"